apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
   name: result-app-service
   app: demo-result-app
spec:
  type: NodePort 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: result-app-pod
    app: demo-result-app