apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-davo
  labels:
    env: test 
spec:
  template: 
   metadata: 
    name: davo-pod
    labels:
      env: test
   spec: 
     containers:
       - name: nginx
         image: nginx:1.7.1
  replicas: 3
  selector:
    matchLabels:
      env: test
