apiVersion: v1
kind: Service
metadata:
  name: myapp-service
# must important part of the file
spec:
 type: NodePort
 ports:
   - targetPort: 80
     port: 80
     nodePort: 30008
 selector: 
#pod definition labels from the pods
    env: test
