apiVersion: v1
kind: ReplicationController
metadata: 
 name: myapp-rc
 labels:
  app: myapp
  type: backend
spec:
 -template: 
  #The pod we want to replicate
  metadata: 
    name: nginx-2
    labels:
      env: production
  spec:
    containers:
      - name: nginx
        image: nginx
  replicas: 2
