apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres-deployment
 labels:
  app: demo-voting-app
  name: postgres-deployment
spec:
 replicas: 1
 selector:
  matchLabels: 
    name: postgres-pod
    app: demo-voting-app
 template:
  metadata:
    name: postgres-pod
    labels:
     name: postgres-pod
     app: demo-voting-app
  spec:
    containers:
      - name: postgres
        image: postgres
        ports: 
         - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "davo"
        - name: POSTGRES_PASSWORD
          value: "davo"
